/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reviewproject;

public class App {
    public static void main(String[] args) {
        BookShelf shelf = getRandomShelf();
        Visitor v = new BookRatio();
        for (Book b : shelf) {
            b.accept(v);
        }
        System.out.println(v.report());
    }

    private static BookShelf getRandomShelf() {
        int numBooks = (int) (Math.random() * 100 + 5);
        BookShelf shelf = new BookShelf();
        for (int i = 0; i < numBooks; i++) {
            Book b = Math.random() > 0.5
                ? new ComicBook(getRandomString(), getRandomString(),
                    Math.random() < 0.5)
                : new TextBook(getRandomString(), getRandomString(),
                    getRandomString());
            shelf.addBook(b);
        }
        return shelf;
    }

    private static String getRandomString() {
        int numChars = (int) (Math.random() * 50 + 1);
        String str = "";
        for (int i = 0; i < numChars; i++) {
            str += (char) (Math.random() * 26 + 97);
        }
        return str;
    }
}
